name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: WiremockStandalone.dll
        # Directory containing files to upload
        path: WiremockStandalone/bin/Release/netcoreapp3.0/win-x64/
